# Generated by Django 5.0.4 on 2026-06-08 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=30, unique=True)),
                ('display_name', models.CharField(max_length=60)),
                ('threshold', models.FloatField(default=0.5)),
                ('severity', models.CharField(choices=[('danger', 'Danger'), ('amber', 'Amber')], max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('sender', models.CharField(max_length=30)),
                ('recipient', models.CharField(blank=True, max_length=30, null=True)),
                ('body', models.TextField()),
                ('preprocessed_body', models.TextField(blank=True)),
                ('timestamp', models.BigIntegerField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['received_at'], name='sentinel_me_receive_33f6e2_idx'), models.Index(fields=['sender'], name='sentinel_me_sender_7cd686_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModerationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_flagged', models.BooleanField(default=False)),
                ('category_scores', models.JSONField()),
                ('flagged_categories', models.JSONField(default=list)),
                ('ar_expl', models.TextField(blank=True)),
                ('en_expl', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('safe', 'Safe'), ('pending', 'Pending'), ('approved', 'Approved'), ('blocked', 'Blocked'), ('escalated', 'Escalated'), ('failed', 'Failed')], db_index=True, default='pending', max_length=15)),
                ('infer_latency_ms', models.FloatField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to=settings.AUTH_USER_MODEL)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='sentinel.message')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=15)),
                ('reason', models.TextField(blank=True)),
                ('ai_scores_at_time', models.JSONField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='sentinel.moderationdecision')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActiveLearningEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_action', models.CharField(max_length=15)),
                ('ai_top_category', models.CharField(max_length=30)),
                ('ai_top_score', models.FloatField()),
                ('is_disagreement', models.BooleanField()),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_entries', to='sentinel.moderationdecision')),
            ],
        ),
        migrations.CreateModel(
            name='ModeratorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('moderator', 'Moderator'), ('senior', 'Senior Moderator'), ('admin', 'Admin')], default='moderator', max_length=20)),
                ('initials', models.CharField(max_length=4)),
                ('tier', models.IntegerField(default=1)),
                ('is_online', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='moderationdecision',
            index=models.Index(fields=['status', 'created_at'], name='sentinel_mo_status_7564dd_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationdecision',
            index=models.Index(fields=['is_flagged', 'created_at'], name='sentinel_mo_is_flag_9250e0_idx'),
        ),
    ]
